export const rrh = {
    page:[
        {
            id:1,
            content:'Once upon a time, there was a little girl who lived in a small town near the forest.\n' +
                '\n' +
                'The little girl always wore a red hood whenever she went out, so everyone called her Little Red Riding Hood.',
            highlight:['hood'],
            image_url:'https://myedmaster.oss-us-east-1.aliyuncs.com/house.jpg',
            audio_url:'https://myedmaster.oss-us-east-1.aliyuncs.com/1.mp3',
        },
        {
            id:2,
            content:'One day, Little Red Riding Hood’s mother told her that her grandmother was sick. Her mother gave her a basket full of treats to give to her grandmother, who lived on the other side of the forest.',
            highlight:[],
            image_url:'https://myedmaster.oss-us-east-1.aliyuncs.com/basket.jpg',
            audio_url:'https://myedmaster.oss-us-east-1.aliyuncs.com/2.mp3',
        },
        {
            id:3,
            content:'“Be careful, Little Red Riding Hood,” her mother warned.\n' +
                '\n' +
                '“You never know what’s hiding in the dark scary woods. Please do not talk to strangers!”\n' +
                '\n' +
                '“I promise to be careful,” Little Red Riding Hood said.',
            highlight:['strangers'],
            image_url:'https://myedmaster.oss-us-east-1.aliyuncs.com/leaving.jpg',
            audio_url:'https://myedmaster.oss-us-east-1.aliyuncs.com/3.mp3',
        },
        {
            id:4,
            content:'But as soon as she left, Little Red Riding Hood forgot all about her promise and spent time picking pretty flowers and chasing colorful butterflies.',
            highlight:['chasing'],
            image_url:'https://myedmaster.oss-us-east-1.aliyuncs.com/butterflies.jpg',
            audio_url:'https://myedmaster.oss-us-east-1.aliyuncs.com/4.mp3',
        },
        {
            id:5,
            content:'',
            highlight:[],
            image_url:'https://myedmaster.oss-us-east-1.aliyuncs.com/',
            audio_url:'https://myedmaster.oss-us-east-1.aliyuncs.com/',
        },
        {
            id:6,
            content:'',
            highlight:[],
            image_url:'https://myedmaster.oss-us-east-1.aliyuncs.com/',
            audio_url:'https://myedmaster.oss-us-east-1.aliyuncs.com/',
        },
        {
            id:7,
            content:'',
            highlight:[],
            image_url:'https://myedmaster.oss-us-east-1.aliyuncs.com/',
            audio_url:'https://myedmaster.oss-us-east-1.aliyuncs.com/',
        },
        {
            id:8,
            content:'',
            highlight:[],
            image_url:'https://myedmaster.oss-us-east-1.aliyuncs.com/',
            audio_url:'https://myedmaster.oss-us-east-1.aliyuncs.com/',
        },
        {
            id:9,
            content:'',
            highlight:[],
            image_url:'https://myedmaster.oss-us-east-1.aliyuncs.com/',
            audio_url:'https://myedmaster.oss-us-east-1.aliyuncs.com/',
        },
        {
            id:10,
            content:'',
            highlight:[],
            image_url:'https://myedmaster.oss-us-east-1.aliyuncs.com/',
            audio_url:'https://myedmaster.oss-us-east-1.aliyuncs.com/',
        },
        {
            id:11,
            content:'',
            highlight:[],
            image_url:'https://myedmaster.oss-us-east-1.aliyuncs.com/',
            audio_url:'https://myedmaster.oss-us-east-1.aliyuncs.com/',
        },
        {
            id:12,
            content:'',
            highlight:[],
            image_url:'https://myedmaster.oss-us-east-1.aliyuncs.com/',
            audio_url:'https://myedmaster.oss-us-east-1.aliyuncs.com/',
        },
        {
            id:13,
            content:'',
            highlight:[],
            image_url:'https://myedmaster.oss-us-east-1.aliyuncs.com/',
            audio_url:'https://myedmaster.oss-us-east-1.aliyuncs.com/',
        },
        {
            id:14,
            content:'',
            highlight:[],
            image_url:'https://myedmaster.oss-us-east-1.aliyuncs.com/',
            audio_url:'https://myedmaster.oss-us-east-1.aliyuncs.com/',
        },
        {
            id:15,
            content:'',
            highlight:[],
            image_url:'https://myedmaster.oss-us-east-1.aliyuncs.com/',
            audio_url:'https://myedmaster.oss-us-east-1.aliyuncs.com/',
        },
        {
            id:16,
            content:'',
            highlight:[],
            image_url:'https://myedmaster.oss-us-east-1.aliyuncs.com/',
            audio_url:'https://myedmaster.oss-us-east-1.aliyuncs.com/',
        },
        {
            id:17,
            content:'',
            highlight:[],
            image_url:'https://myedmaster.oss-us-east-1.aliyuncs.com/',
            audio_url:'https://myedmaster.oss-us-east-1.aliyuncs.com/',
        },
        {
            id:18,
            content:'',
            highlight:[],
            image_url:'https://myedmaster.oss-us-east-1.aliyuncs.com/',
            audio_url:'https://myedmaster.oss-us-east-1.aliyuncs.com/',
        },
        {
            id:19,
            content:'',
            highlight:[],
            image_url:'https://myedmaster.oss-us-east-1.aliyuncs.com/',
            audio_url:'https://myedmaster.oss-us-east-1.aliyuncs.com/',
        },
        {
            id:20,
            content:'',
            highlight:[],
            image_url:'https://myedmaster.oss-us-east-1.aliyuncs.com/',
            audio_url:'https://myedmaster.oss-us-east-1.aliyuncs.com/',
        },
        {
            id:21,
            content:'',
            highlight:[],
            image_url:'https://myedmaster.oss-us-east-1.aliyuncs.com/',
            audio_url:'https://myedmaster.oss-us-east-1.aliyuncs.com/',
        },


    ]
}